# Python code to calculate ratio matrices and largest eigenvectors
The following code is here to demonstrate two things:

1. Calculating the priority vector from the pairwise comparison matrix
2. Calcualting the ratio matrix from a priority vector.  That ratio matrix's priority vector will be the one we started with.

In [21]:
import numpy as np
from IPython.core.display import display, HTML

# Define the largest eigenvector and ratio matrix functions

In [18]:
def largesteigen(mat, ret_eigenval = False, max_err = 1e-10, max_count=1000):
    #Turn a list of lists into a numpy array if necessary
    if isinstance(mat, (list, tuple)):
        mat = np.array(mat)
    n = mat.shape[0]
    last_step = np.array([1.0/n]*n)
    next_step = np.zeros([n])
    np.matmul(mat, last_step, next_step)
    last_sum = sum(next_step)
    np.multiply(1.0/last_sum, next_step, next_step)
    diff = sum(abs(next_step - last_step))
    step = 0
    while (diff > max_err) and (step < max_count):
        np.matmul(mat, last_step, next_step)
        last_sum = sum(next_step)
        np.multiply(1.0/last_sum, next_step, next_step)
        tmp = last_step
        last_step=next_step
        next_step=tmp
        diff = sum(abs(next_step - last_step))
    if ret_eigenval:
        return (val, vec)
    else:
        return next_step

def ratiomatrix(pvec):
    if isinstance(pvec, (list, tuple)):
        n = len(pvec)
    else:
        n = pvec.shape[0]
    rval = np.identity(n=n, dtype=float)
    for row in range(n):
        for col in range(row+1, n):
            rval[row][col]=pvec[row]/pvec[col]
            rval[col][row]=pvec[col]/pvec[row]
    return rval

# A function to use for examples
This function does the following

1. Starts with priority vector
2. Normalizes it, and prints the result
3. Calcualtes the ratio matrix and prints the result
4. Calculates the priority vector of the matrix and prints the result

Note that steps 2 and 4 should have the same values

In [28]:
def example_show(p):
    ap = np.array(p)
    mat = ratiomatrix(p)
    display(HTML("<h3>Original Vector Normalized</h3>"))
    display(ap/sum(ap))    
    display(HTML("<h3>Ratio Matrix</h3>"))
    display(mat)
    newp = largesteigen(mat)
    display(HTML("<h3>New Priority Vector</h3>"))
    display(newp)

# Examples

In [30]:
example_show((1, 2, 3))

array([ 0.16666667,  0.33333333,  0.5       ])

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 2.        ,  1.        ,  0.66666667],
       [ 3.        ,  1.5       ,  1.        ]])

array([ 0.16666667,  0.33333333,  0.5       ])

In [31]:
example_show([.1, .3, .4, .2])

array([ 0.1,  0.3,  0.4,  0.2])

array([[ 1.        ,  0.33333333,  0.25      ,  0.5       ],
       [ 3.        ,  1.        ,  0.75      ,  1.5       ],
       [ 4.        ,  1.33333333,  1.        ,  2.        ],
       [ 2.        ,  0.66666667,  0.5       ,  1.        ]])

array([ 0.1,  0.3,  0.4,  0.2])